const Actions = {
  SET_LIMITS: 'SET_LIMITS',
  SET_CURRENT_AMOUNT: 'SET_CURRENT_AMOUNT',
  SET_CURRENT_TERM: 'SET_CURRENT_TERM',
  SET_RESULTS: 'SET_RESULTS',
  SET_INITIAL_VALUES: 'SET_INITIAL_VALUES',
};

export default Actions;
